version: '3.7'
services:
  db:
    image: postgres
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=db-api
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
