version: '3.7'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=aqa71docker_db_1
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
